buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://cdn.fox2code.com/maven' }
    }
    dependencies {
        classpath('com.fox2code.FoxLoader:dev:2.0-alpha32')
    }
}

apply plugin: 'foxloader.dev'

group = 'com.i8ux100'
version = '2.0-a1'

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

jar {
    from "LICENSE"
}

foxloader {
    modId = "companioncube"
    modName = "Portal Companion Cube"
    modIcon = "assets/companioncube/icon.png"
    modVersion = project.version
    modAuthors = "Emilyn (i8ux100)"
    modWebsite = "https://github.com/Fox2Code/FoxLoaderExampleMod"
    modMain = "com.i8ux100.companioncube.CompanionCubeMod"
    modDesc("Adds Portal's Companion Cube to Reindev!")
}
